# https://www.appveyor.com/docs/appveyor-yml

# to disable automatic builds
build: off
branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

shallow_clone: true
clone_depth: 1

cache:
  - node_modules -> package.json

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    # - PYTHON: "C:\\Python27"
    # - PYTHON: "C:\\Python36-x64"

matrix:
  fast_finish: true

install:
  install:
  # We need wheel installed to build wheels
  # - %PYTHON%\\python.exe -m pip install wheel
  - python --version
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run test
